# Code Generated by Sidekick is for learning and experimentation purposes only.
import json, os, uuid, boto3
from botocore.exceptions import ClientError

ENDPOINT_ARN = os.getenv(
    "AGENTCORE_RUNTIME_ENDPOINT_ARN",
    "arn:aws:bedrock-agentcore:us-east-1:662403250828:runtime/agentcore_memory_mcp-WQSSA27ROG/runtime-endpoint/DEFAULT",
)
REGION = os.getenv("AWS_REGION", "us-east-1")

agent_runtime_arn, qualifier = ENDPOINT_ARN.split("/runtime-endpoint/", 1)

payload_obj = {
    "tool": "retrieve_memory",
    "args": {"query": "user preferences about food", "max_results": 2, "actor_id": "my-user-id"},
}

client = boto3.client("bedrock-agentcore", region_name=REGION)

try:
    resp = client.invoke_agent_runtime(
        agentRuntimeArn=agent_runtime_arn,
        qualifier=qualifier,
        runtimeSessionId=str(uuid.uuid4()),
        contentType="text/event-stream;q=1.0, application/json;q=0.9",
        accept="text/event-stream;q=1.0, application/json;q=0.9",   # switch to "text/event-stream" if your runtime streams
        payload=json.dumps(payload_obj).encode("utf-8"),
    )
    print((resp["response"].read() or b"").decode("utf-8", errors="replace"))
except ClientError as e:
    print(json.dumps(e.response, indent=2, default=str))
    raise
