"""
Author: Sarvagya Meel
Email: sarvagyameel2@gmail.com
Date: 11/02/26
"""

# Code Generated by Sidekick is for learning and experimentation purposes only.
import os
import itertools
from typing import Any, Dict, Optional

import requests

# Code Generated by Sidekick is for learning and experimentation purposes only.

import inspect
from mcp.server.fastmcp.server import FastMCP
# print("FastMCP.run signature:", inspect.signature(FastMCP.run))
# print(inspect.getsource(FastMCP.run))
# print(inspect.getsource(FastMCP.run_streamable_http_async))

_id = itertools.count(1)


class MCPError(RuntimeError):
    pass


import json

def pretty_print_mcp_from_r_text(r_text: str) -> None:
    # Handles either plain JSON OR SSE with `data: {...}` JSON-RPC payloads.
    s = (r_text or "").strip()

    # Plain JSON case
    if s.startswith("{") or s.startswith("["):
        obj = json.loads(s)
        print(json.dumps(obj, indent=2, ensure_ascii=False, sort_keys=True))
        return

    # SSE case: collect all `data:` lines up to the first blank line (one event)
    data_lines = []
    for line in r_text.splitlines():
        if not line.strip():  # blank line => end of event
            break
        if line.startswith("data:"):
            data_lines.append(line[len("data:"):].lstrip())

    if not data_lines:
        raise ValueError("No JSON found (no SSE data: lines).")

    obj = json.loads("\n".join(data_lines))
    print(json.dumps(obj, indent=2, ensure_ascii=False, sort_keys=True))
    return obj

# Example:
# pretty_print_mcp_from_r_text(r.text)
def jsonrpc(endpoint: str, method: str, params: Dict[str, Any], *, timeout_s: float = 60.0) -> Any:
    payload = {
        "jsonrpc": "2.0",
        "id": next(_id),
        "method": method,
        "params": params,
    }
    headers = {
        "content-type": "application/json",
        "accept": "application/vnd.mcp+json, application/json, text/event-stream",
    }
    r = requests.post(endpoint,headers=headers, json=payload, timeout=timeout_s)
    print(r.status_code)
    r.raise_for_status()
    resp = pretty_print_mcp_from_r_text(r.text)

    if "error" in resp and resp["error"]:
        raise MCPError(f"JSON-RPC error: {resp['error']}")
    return resp.get("result")


def list_tools(endpoint: str) -> Any:
    return jsonrpc(endpoint, "tools/list", {})


def call_tool(endpoint: str, name: str, arguments: Optional[Dict[str, Any]] = None) -> Any:
    return jsonrpc(
        endpoint,
        "tools/call",
        {"name": name, "arguments": arguments or {}},
    )



if __name__ == "__main__":
    # Set this to your FastMCP stateless HTTP endpoint (and path, if applicable).
    # Examples vary by deployment; keep it in an env var to avoid hardcoding.
    # endpoint = os.environ["MCP_ENDPOINT"]
    endpoint = "http://127.0.0.1:8001/mcp"
    print("\nListing tools...")
    tools = list_tools(endpoint)
    print(tools)

    print("\nCalling server_info...")
    result = call_tool(endpoint, "server_info", {})
    print(result)

    print("\nRetrieving memory...")
    result = call_tool(endpoint, "retrieve_memory", {"query":"what are my food preferences", "max_results": 2})
    print(result)

    # print("\nStoring memory...")
    # result = call_tool(endpoint, "store_interaction", {})
    # print(result)


