"""
Author: Sarvagya Meel
Email: sarvagyameel2@gmail.com
Date: 11/02/26
"""

# Code Generated by Sidekick is for learning and experimentation purposes only.
import logging
import os
from http.client import responses

from mcp.server.fastmcp import FastMCP
from bedrock_agentcore.memory import MemoryClient

from memory_util import MemoryConfig, MemoryManager, retrieve_memories_for_actor

# -------- Logging
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO").upper()
logging.basicConfig(level=getattr(logging, LOG_LEVEL, logging.INFO),
                    format="%(asctime)s %(levelname)s %(name)s - %(message)s")
logger = logging.getLogger("mcp.memory.server")

# -------- Config
MCP_HOST = os.getenv("MCP_HOST", "0.0.0.0")
MCP_PORT = int(os.getenv("MCP_PORT", "8000"))
ACTOR_ID_ENV = os.getenv("AGENTCORE_ACTOR_ID", "my-user-id")
MEMORY_CONFIG_PATH = os.getenv("MEMORY_CONFIG_PATH", "../config/memory-config.json")

# Initialize
memory_config = MemoryConfig.from_file_or_env(MEMORY_CONFIG_PATH)
memory_client = MemoryClient(region_name="us-east-1")
memory_manager = MemoryManager(memory_config=memory_config, memory_client=memory_client, default_actor_id=ACTOR_ID_ENV)

# Preflight: verify we can touch memory (won’t crash container later)
try:
    _ = retrieve_memories_for_actor(
        memory_id=memory_config.memory_id,
        actor_id=ACTOR_ID_ENV,
        search_query="__startup_check__",
        memory_client=memory_client,
        max_results=1,
    )
    logger.info("Startup memory check passed", extra={"memory_id": memory_config.memory_id})
except Exception as e:
    logger.warning("Startup memory check failed; server will still start", exc_info=True)

# MCP Server
mcp = FastMCP("agentcore_memory_mcp", host=MCP_HOST, port=MCP_PORT, stateless_http=True)


@mcp.tool()
def retrieve_memory(
    query: str,
    max_results: int = 10,
    actor_id: str = ACTOR_ID_ENV,
) :
    """
    Retrieve memories from AgentCore memory store based on a search query.
    """
    if not query or not isinstance(query, str):
        return "ERROR: 'query' must be a non-empty string"

    try:
        results = retrieve_memories_for_actor(
            memory_id=memory_config.memory_id,
            actor_id=actor_id,
            search_query=query,
            memory_client=memory_client,
            max_results=max_results,
        )
        if not results:
            return "No relevant memories found."

        lines = []
        for i, m in enumerate(results, 1):
            content = m.get("content", m.get("text", ""))
            meta = m.get("metadata", {})
            line = f"{i}. {content}".strip()
            print(line)
            lines.append(line)
            if meta:
                line += f" (metadata: {meta})"
            lines.append(line)
        response_cntx =  {"text":"\n".join(lines),
                          "status" :200}

    except Exception as e:
        logger.error("retrieve_memory failed", exc_info=True)
        response_cntx = {"text":f"ERROR: {e}",
                        "status": 400}
    return response_cntx


@mcp.tool()
def store_interaction(
    user_msg: str,
    assistant_msg: str,
    actor_id: str = ACTOR_ID_ENV,
    session_id: str = None,
):
    """
    Store a user/assistant turn to AgentCore memory.
    """
    if not user_msg or not assistant_msg:
        return "ERROR: user_msg and assistant_msg are required"

    try:
        ok = memory_manager.store_conversation(
            user_input=user_msg,
            response=assistant_msg,
            actor_id=actor_id,
            session_id=session_id or memory_config.default_session_id,
        )
        response_cntx = {"text": "PASS" if ok else "store_conversation returned Fals",
                         "status": 200}

    except Exception as e:
        logger.error("store_interaction failed", exc_info=True)
        response_cntx = {"text":f"ERROR: {e}",
                        "status": 400}
    return response_cntx



if __name__ == "__main__":
    mcp.run()

