# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Author: Sarvagya Meel
Email: sarvagyameel2@gmail.com
Date: 11/02/26
"""

import logging
import os
from typing import Any, Dict, List, Optional

from mcp.server.fastmcp import FastMCP
from bedrock_agentcore.memory import MemoryClient

from memory_util import MemoryConfig, MemoryManager, retrieve_memories_for_actor
from tool_response import classify_exception, ToolResponse
import json
from typing import Any, Dict

from server_info_util import collect_server_info

SERVICE_NAME = "agentcore_memory_mcp"
TOOL_NAMES = ["retrieve_memory", "store_interaction", "server_info"]  # keep in sync

# -------- Logging
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO").upper()
logging.basicConfig(
    level=getattr(logging, LOG_LEVEL, logging.INFO),
    format="%(asctime)s %(levelname)s %(name)s - %(message)s",
)
logger = logging.getLogger("mcp.memory.server")

# -------- Config
MCP_HOST = os.getenv("MCP_HOST", "127.0.0.1")
MCP_PORT = int(os.getenv("MCP_PORT", "8001"))
ACTOR_ID_ENV = os.getenv("AGENTCORE_ACTOR_ID", "default_mcp")
MEMORY_CONFIG_PATH = os.getenv("MEMORY_CONFIG_PATH", "../config/memory-config.json")

# Initialize
memory_config = MemoryConfig.from_file_or_env(MEMORY_CONFIG_PATH)
memory_client = MemoryClient(region_name="us-east-1")
memory_manager = MemoryManager(
    memory_config=memory_config,
    memory_client=memory_client,
)

# Preflight: verify we can touch memory (won’t crash container later)
try:
    _ = retrieve_memories_for_actor(
        memory_id=memory_config.memory_id,
        actor_id=ACTOR_ID_ENV,
        search_query="__startup_check__",
        memory_client=memory_client,
        max_results=1,
    )
    logger.info("Startup memory check passed", extra={"memory_id": memory_config.memory_id})
except Exception:
    logger.warning("Startup memory check failed; server will still start", exc_info=True)

# MCP Server
mcp = FastMCP("agentcore_memory_mcp", host=MCP_HOST, port=MCP_PORT, stateless_http=True)
def _server_info_payload() -> Dict[str, Any]:
    return collect_server_info(
        mcp_host=MCP_HOST,
        mcp_port=MCP_PORT,
        service_name=SERVICE_NAME,
        tool_names=TOOL_NAMES,
    )
# Log at startup (safe, single line JSON)
logger.info("Server starting: %s", json.dumps(_server_info_payload(), default=str))

@mcp.tool()
def server_info(session_id:str) -> ToolResponse:
    tool = "server_info"
    try:
        return ToolResponse.ok(tool, "Server info.", data={"server": _server_info_payload()}, meta=_base_meta(session_id=session_id), status=200)
    except Exception as e:
        logger.error("server_info failed", exc_info=True)
        return ToolResponse.err(tool, "Failed to collect server info.", code="INTERNAL", status=500, details={"exception_type": type(e).__name__}, meta=_base_meta(session_id=session_id))


def _base_meta(**kwargs: Any) -> Dict[str, Any]:
    meta = {
        "memory_id": memory_config.memory_id,
    }
    meta.update({k: v for k, v in kwargs.items() if v is not None})
    return meta


@mcp.tool()
def retrieve_memory(query: str, max_results: int = 10,
                    actor_id: str = ACTOR_ID_ENV,
                    session_id: Optional[str] = None
                    ) -> ToolResponse:
    tool = "retrieve_memory"
    if not isinstance(query, str) or not query.strip():
        return ToolResponse.err(
            tool,
            "Invalid input: 'query' must be a non-empty string.",
            code="VALIDATION_ERROR",
            status=400,
            meta=_base_meta(actor_id=actor_id, max_results=max_results,session_id=session_id),
        )

    if not isinstance(max_results, int) or max_results <= 0 or max_results > 100:
        return ToolResponse.err(
            tool,
            "Invalid input: 'max_results' must be an int (1..100).",
            code="VALIDATION_ERROR",
            status=400,
            meta=_base_meta(actor_id=actor_id, query=query, max_results=max_results,session_id=session_id),
        )

    try:
        results = retrieve_memories_for_actor(
            memory_id=memory_config.memory_id,
            actor_id=actor_id,
            search_query=query.strip(),
            memory_client=memory_client,
            max_results=max_results,
        ) or []

        formatted_output = []
        for i, entry in enumerate(results, 1):
            # 1. Safe Extraction with default fallbacks to avoid 'None'
            content_obj = entry.get("content") or {}
            raw_text = content_obj.get("text") or "No content available"
            strategy = entry.get("memoryStrategyId") or "GeneralStore"

            # 2. Try to parse nested JSON if the text is a JSON string
            display_text = raw_text
            if raw_text.strip().startswith("{"):
                try:
                    parsed_json = json.loads(raw_text)
                    # Prioritize 'context' or 'preference' fields if they exist
                    display_text = parsed_json.get("context") or parsed_json.get("preference") or raw_text
                except json.JSONDecodeError:
                    pass  # Keep as raw text if not valid JSON

            # 3. Clean up XML-style tags if present (e.g., <topic>)
            if "<topic" in display_text:
                display_text = display_text.replace("<topic name=", "Topic: ").replace("</topic>", "").replace('">',
                                                                                                               " - ")

            # 4. Handle Metadata Safely (Ensure it's never None)
            metadata = entry.get("metadata") or {}
            score = entry.get("score", 0.0)

            # 5. Build the final string block
            # record = (
            #     f"Memory #{i} [{strategy}]\n"
            #     f"Content: {display_text.strip()}\n"
            #     f"Relevance: {score:.4f}"
            # )
            record_obj = {
                "memory_index": i,
                "strategy": strategy,
                "content": display_text.strip(),
                "relevance": round(float(score), 6),
            }
            formatted_output.append(record_obj)
            # print(i, record)
            # formatted_output.append(record)
        # data = "\n\n".join(formatted_output)
        json_payload = {"memories": formatted_output}
        data = json.dumps(json_payload, ensure_ascii=False, indent=2)
        # Final safety check: Join with double newline for readability

        message = "No memories found." if not data else "Memories retrieved."
        return ToolResponse.ok(
            tool,
            message,
            data={"items": formatted_output},
            meta=_base_meta(actor_id=actor_id, query=query, max_results=max_results, count=len(formatted_output),session_id=session_id),
            status=200,
        )

    except Exception as e:
        code, status, details = classify_exception(e)
        logger.error("retrieve_memory failed", exc_info=True, extra={"code": code, "status": status})
        return ToolResponse.err(
            tool,
            "Failed to retrieve memory.",
            code=code,
            status=status,
            details=details,
            meta=_base_meta(actor_id=actor_id, query=query, max_results=max_results,session_id=session_id),
        )


@mcp.tool()
def store_interaction(
    user_msg: str,
    assistant_msg: str,
    actor_id: str = ACTOR_ID_ENV,
    session_id: Optional[str] = None,
) ->ToolResponse:
    tool = "store_interaction"

    if not isinstance(user_msg, str) or not user_msg.strip():
        return ToolResponse.err(
            tool,
            "Invalid input: 'user_msg' is required.",
            code="VALIDATION_ERROR",
            status=400,
            meta=_base_meta(actor_id=actor_id, session_id=session_id),
        )

    if not isinstance(assistant_msg, str) or not assistant_msg.strip():
        return ToolResponse.err(
            tool,
            "Invalid input: 'assistant_msg' is required.",
            code="VALIDATION_ERROR",
            status=400,
            meta=_base_meta(actor_id=actor_id, session_id=session_id),
        )

    try:
        ok_flag = memory_manager.store_conversation(
            user_input=user_msg,
            response=assistant_msg,
            actor_id=actor_id,
            session_id=session_id or memory_config.default_session_id,
        )

        if not ok_flag:
            return ToolResponse.err(
                tool,
                "Store failed: store_conversation returned False.",
                code="STORE_FAILED",
                status=502,
                meta=_base_meta(actor_id=actor_id, session_id=session_id or memory_config.default_session_id),
            )

        return ToolResponse.ok(
            tool,
            "Stored interaction.",
            data={"stored": True},
            meta=_base_meta(actor_id=actor_id, session_id=session_id or memory_config.default_session_id),
            status=200,
        )

    except Exception as e:
        code, status, details = classify_exception(e)
        logger.error("store_interaction failed", exc_info=True, extra={"code": code, "status": status})
        return ToolResponse.err(
            tool,
            "Failed to store interaction.",
            code=code,
            status=status,
            details=details,
            meta=_base_meta(actor_id=actor_id, session_id=session_id),
        )

if __name__ == "__main__":
    mcp.run(transport="streamable-http")

