"""
Author: Sarvagya Meel
Email: sarvagyameel2@gmail.com
Date: 11/02/26
"""

# Code Generated by Sidekick is for learning and experimentation purposes only.
import json
import logging
import time
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from bedrock_agentcore.memory import MemoryClient  # Provided by AgentCore runtime


def _log() -> logging.Logger:
    return logging.getLogger("agentcore.memory")


@dataclass(frozen=True)
class MemoryConfig:
    memory_id: str
    default_session_id: str = "DEFAULT"

    @staticmethod
    def from_file_or_env(config_path: Optional[str] = None) -> "MemoryConfig":
        """
        Loads config from JSON file at MEMORY_CONFIG_PATH or provided path.
        Expects: { "memory_id": "your_store_id", "default_session_id": "DEFAULT" }
        """
        # import os
        #
        # path = config_path or os.getenv("MEMORY_CONFIG_PATH", "memory-config.json")
        # p = Path(path)
        #
        #
        # # If a caller passed a relative path, make it relative to this file's folder
        # if not p.is_absolute():
        #     p = Path(__file__).resolve().parent / p
        #
        #
        # if not p.exists():
        #     raise FileNotFoundError(f"Memory config not found at {p.resolve()}")
        #
        # data = json.loads(p.read_text(encoding="utf-8"))
        memory_id = "MyAgentMemory20260211160131-gMGdB67nD0" #data.get("memory_id")
        if not memory_id or memory_id == "REPLACE_ME_MEMORY_ID":
            raise ValueError("memory-config.json missing valid 'memory_id'")

        return MemoryConfig(
            memory_id=memory_id,
            default_session_id= "default_memory_util",
        )


def _pick(obj: Any, names: List[str]) -> Optional[Any]:
    for n in names:
        if hasattr(obj, n) and callable(getattr(obj, n)):
            return getattr(obj, n)
    return None


class MemoryManager:
    """
    Unified memory manager that is defensive about AgentCore SDK differences.
    - Stores conversation turns (user/assistant)
    - Retrieves last-k turns for context
    - Searches long-term memories
    """

    def __init__(
        self,
        memory_config: Optional[MemoryConfig] = None,
        default_actor_id: str = "default-user",
        default_session_id: str = "default-session",
        max_conversation_turns: int = 100,
        logger: Optional[logging.Logger] = None,
        memory_client: Optional[MemoryClient] = None,
    ):
        self.logger = logger or _log()
        self.config = memory_config or MemoryConfig.from_file_or_env()
        print(f"Memory config gg: {self.config}")
        self.default_actor_id = default_actor_id
        self.default_session_id = default_session_id
        self.max_conversation_turns = max_conversation_turns
        self.client = memory_client or MemoryClient()
        self._initialized_sessions: Dict[str, bool] = {}

        self.logger.info(
            "MemoryManager ready",
            extra={"memory_id": self.config.memory_id, "default_session_id": self.default_session_id},
        )

    # -------- Public API

    def get_memory_context(
        self,
        user_input: str,
        actor_id: Optional[str] = None,
        session_id: Optional[str] = None,
        load_conversation_context: bool = True,
        retrieve_relevant_memories: bool = True,
    ) -> str:
        actor_id = actor_id or self.default_actor_id
        session_id = session_id or self.default_session_id
        session_key = f"{actor_id}:{session_id}"
        parts: List[str] = []

        if load_conversation_context and not self._initialized_sessions.get(session_key, False):
            convo = self._load_conversation_context(actor_id, session_id)
            if convo:
                parts.append(f"Recent conversation:\n{convo}")
            self._initialized_sessions[session_key] = True

        if retrieve_relevant_memories and user_input:
            items = self.search_memories(actor_id=actor_id, query=user_input, limit=10)
            if items:
                parts.append("Relevant long-term memory context:\n" + format_memory_context(items))

        return "\n\n".join(parts) if parts else ""

    def store_conversation(
        self,
        user_input: str,
        response: str,
        actor_id: Optional[str] = None,
        session_id: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> bool:
        if not user_input or not response:
            self.logger.warning("Missing user_input or response; skip store")
            return False
        ts = int(time.time())
        turn_id = str(uuid.uuid4())

        # Preferred: create_event(memory_id, actor_id, session_id, messages=[(text, role), ...])
        messages = [(user_input, "USER"), (response, "ASSISTANT")]
        create_event = _pick(self.client, ["create_event", "createEvent", "append_event", "appendEvent"])

        if create_event:
            try:
                create_event(
                    memory_id=self.config.memory_id,
                    actor_id=actor_id,
                    session_id=session_id,
                    messages=messages,
                    # metadata=metadata or {"turn_id": turn_id, "ts": ts},
                )
                self.logger.info("Successfully stored conversation in memory")
                return True
            except Exception as e:
                self.logger.warning("create_event failed; will fallback", exc_info=True)

        # Fallback: upsert a single combined text
        store_fallback = _pick(
            self.client,
            ["store_memory", "create_memory", "upsert_memory", "write_memory", "put_memory"],
        )
        if store_fallback:
            combined = f"USER: {user_input}\nASSISTANT: {response}"
            try:
                store_fallback(
                    memory_id=self.config.memory_id,
                    actor_id=actor_id,
                    session_id=session_id,
                    content=combined,
                    metadata=metadata or {"turn_id": turn_id, "ts": ts, "type": "conversation_turn"},
                )
                return True
            except Exception as e:
                self.logger.error("Fallback store_memory failed", exc_info=True)
                return False

        self.logger.error("No supported memory write method found on MemoryClient")
        return False

    def search_memories(
        self, actor_id: str, query: str, limit: int = 10
    ) -> List[Dict[str, Any]]:
        """
        Cross-version retrieval: try multiple search/retrieve signatures.
        """
        # P1: retrieve_memories(memory_id, actor_id, query, limit)
        for method in [
            ("retrieve_memories", dict(memory_id=self.config.memory_id, actor_id=actor_id, query=query, limit=limit)),
            ("search_memories", dict(memory_id=self.config.memory_id, actor_id=actor_id, query=query, limit=limit)),
            ("search", dict(memory_id=self.config.memory_id, actor_id=actor_id, text=query, k=limit)),
            # Some variants use 'namespace' to scope by actor
            ("retrieve_memories", dict(memory_id=self.config.memory_id, namespace=f"/actor/{actor_id}/", query=query)),
        ]:
            name, kwargs = method
            fn = getattr(self.client, name, None)
            if not callable(fn):
                continue
            try:
                res = fn(**kwargs)
                if res is None:
                    return []
                if isinstance(res, list):
                    return res[:limit] if limit > 0 else res
                if isinstance(res, dict):
                    if "memories" in res and isinstance(res["memories"], list):
                        return res["memories"][:limit] if limit > 0 else res["memories"]
                    if "items" in res and isinstance(res["items"], list):
                        return res["items"][:limit] if limit > 0 else res["items"]
                # Generic normalize
                return [{"content": str(res), "metadata": {"_raw": True}}]
            except Exception:
                continue

        self.logger.warning("No supported memory search method worked")
        return []

    # -------- Internals

    def _load_conversation_context(self, actor_id: str, session_id: str) -> str:
        """
        Retrieve last-k turns across various SDK names.
        """
        attempts: List[Tuple[str, Dict[str, Any]]] = [
            ("get_last_k_turns", dict(memory_id=self.config.memory_id, actor_id=actor_id, session_id=session_id, k=self.max_conversation_turns)),
            ("list_events", dict(memory_id=self.config.memory_id, actor_id=actor_id, session_id=session_id, limit=self.max_conversation_turns)),
            ("get_conversation", dict(memory_id=self.config.memory_id, actor_id=actor_id, session_id=session_id, limit=self.max_conversation_turns)),
        ]
        for name, kwargs in attempts:
            fn = getattr(self.client, name, None)
            if not callable(fn):
                continue
            try:
                rows = fn(**kwargs) or []
                return _format_conversation_rows(rows)
            except Exception:
                continue
        return ""


def _format_conversation_rows(rows: Any) -> str:
    """
    Accepts a list of turns or events with role/content, returns printable transcript.
    """
    out: List[str] = []

    # Case: rows is List[List[{role, content}]]
    if rows and isinstance(rows, list) and isinstance(rows[0], list):
        for turn in rows:
            for m in turn:
                role = m.get("role", "UNKNOWN")
                content = _coerce_content(m.get("content", ""))
                out.append(f"{role}: {content}")
        return "\n".join(out)

    # Case: rows is flat List[{role, content}]
    if rows and isinstance(rows, list) and isinstance(rows[0], dict):
        for m in rows:
            role = m.get("role", m.get("author", "UNKNOWN"))
            content = _coerce_content(m.get("content", m.get("text", "")))
            out.append(f"{role}: {content}")
        return "\n".join(out)

    # Fallback
    return str(rows)


def _coerce_content(content: Any) -> str:
    if isinstance(content, str):
        # Attempt to unwrap serialized JSON payloads
        if content.startswith("{") or content.startswith("["):
            try:
                return json.dumps(json.loads(content), ensure_ascii=False)
            except Exception:
                return content
        return content
    try:
        return json.dumps(content, ensure_ascii=False)
    except Exception:
        return str(content)


def retrieve_memories_for_actor(
    memory_id: str,
    actor_id: str,
    search_query: str,
    memory_client: Optional[MemoryClient] = None,
    max_results: int = 10,
) -> List[Dict[str, Any]]:
    """
    Convenience function if you prefer a stateless call from tools.
    """
    mgr = MemoryManager(memory_config=MemoryConfig(memory_id=memory_id), memory_client=memory_client)
    return mgr.search_memories(actor_id=actor_id, query=search_query, limit=max_results)


def format_memory_context(memories: List[Dict[str, Any]]) -> str:
    if not memories:
        return "No relevant memories found."
    lines: List[str] = []
    for i, m in enumerate(memories, 1):
        content = m.get("content", m.get("text", ""))
        meta = m.get("metadata", {})
        line = f"{i}. {content}".strip()
        if meta:
            line += f" (metadata: {meta})"
        lines.append(line)
    return "\n".join(lines)

