[project]
name = "agentcore-memory-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bedrock-agentcore>=0.1.3",
    "bedrock-agentcore-starter-toolkit",  # provides: bedrock_agentcore_starter_toolkit
    "mcp[cli]>=1.13.1",
    "fastapi"
]

[dependency-groups]
dev = [
    "vulture>=2.14",
    "ruff>=0.8.0",
]
