"""
Author: Sarvagya Meel
Email: sarvagyameel2@gmail.com
Date: 11/02/26
"""

# Code Generated by Sidekick is for learning and experimentation purposes only.
from __future__ import annotations
from __future__ import annotations

import json
from typing import Any, Dict, Optional, TypedDict, Tuple

from typing import Any, Dict, List, Optional, Union

from bedrock_agentcore_starter_toolkit.cli.memory.commands import status
from pydantic import BaseModel, Field, ConfigDict
from pygments.lexers import data
# 1. Base Types
RequestId = Union[str, int, None]

# 2. Define the MCP Content Item (What MCP clients expect)
class MCPContent(BaseModel):
    type: str = "text"
    text: str

# 3. Define the MCP Result (The 'result' key in JSON-RPC)
class MCPResult(BaseModel):
    content: List[MCPContent]
    is_error: bool = Field(default=False, alias="isError")


# 4. The Final JSON-RPC Response Model
class ToolResponse(BaseModel):
    jsonrpc: str = "2.0"
    id: RequestId= None
    result: MCPResult= Field(default_factory=MCPResult)
    status: int = 200
    message: str = ""
    session_id: str = ""
    tool_name: str

    @classmethod
    def ok(
        cls,
        tool_name: str,
        message: str,
        status: int = 200,
        request_id: RequestId = None,
        data: Optional[Dict[str, Any]] = None,
        meta: Optional[Dict[str, Any]] = None,
    ) -> ToolResponse:
        """
        Creates a successful JSON-RPC response.
        Ensures metadata and data are dictionaries (never None).
        """
        # Internal payload as a clean dictionary
        payload = {
            "data": data or {},
            "metadata": meta or {} # Critical: ensures 'object' type
        }
        return cls(
            jsonrpc="2.0",
            tool_name=tool_name,
            id=request_id,
            status=status,
            message=message,
            result=MCPResult(
                content=[MCPContent(text=json.dumps(payload))],
                isError=False
            )
        )

    @classmethod
    def err(
        cls,
        tool_name: str,
        message: str,
        status: int = 500,
        request_id: RequestId = None,
        details: Optional[Dict[str, Any]] = None,
        meta: Optional[Dict[str, Any]] = None,
        code: str = "INTERNAL",
    ) -> ToolResponse:
        """Creates a failure JSON-RPC response."""
        payload = {
            "data": {
                "code": code,
                "message": message,
                "details": details or {},
            },
            "metadata": meta or {}  # Critical: ensures 'object' type
        }
        return cls(
            id=request_id,
            status=status,
            message=message,
            tool_name=tool_name,
            result=MCPResult(
                content=[MCPContent(text=json.dumps(payload))],
                isError=True)
        )

def classify_exception(e: Exception) -> Tuple[str, int, Dict[str, Any]]:
    """
    Best-effort mapping of AWS/botocore errors to stable (code, status, details).
    """
    details: Dict[str, Any] = {"exception_type": type(e).__name__}

    # botocore is typical for AWS SDK clients; keep optional.
    try:
        from botocore.exceptions import ClientError, EndpointConnectionError, NoCredentialsError, PartialCredentialsError  # type: ignore
    except Exception:
        ClientError = None  # type: ignore
        EndpointConnectionError = None  # type: ignore
        NoCredentialsError = None  # type: ignore
        PartialCredentialsError = None  # type: ignore

    if ClientError is not None and isinstance(e, ClientError):  # type: ignore[arg-type]
        resp = e.response or {}
        err_info = resp.get("Error", {}) if isinstance(resp, dict) else {}
        aws_code = err_info.get("Code")
        aws_msg = err_info.get("Message")

        details.update(
            {
                "aws_error_code": aws_code,
                "aws_error_message": aws_msg,
                "aws_operation": getattr(e, "operation_name", None),
            }
        )

        if aws_code in ("AccessDeniedException", "AccessDenied", "UnauthorizedOperation"):
            return "ACCESS_DENIED", 403, details
        if aws_code in ("ValidationException", "InvalidParameterException"):
            return "VALIDATION_ERROR", 400, details
        if aws_code in ("ThrottlingException", "Throttling", "TooManyRequestsException"):
            return "THROTTLED", 429, details

        return "AWS_CLIENT_ERROR", 502, details

    if EndpointConnectionError is not None and isinstance(e, EndpointConnectionError):  # type: ignore[arg-type]
        return "UPSTREAM_UNREACHABLE", 502, details

    if NoCredentialsError is not None and isinstance(e, (NoCredentialsError, PartialCredentialsError)):  # type: ignore[arg-type]
        return "NO_CREDENTIALS", 401, details

    if isinstance(e, (ValueError, TypeError)):
        return "VALIDATION_ERROR", 400, details

    return "INTERNAL", 500, details