"""
Author: Sarvagya Meel
Email: sarvagyameel2@gmail.com
Date: 22/10/25
"""
# Code Generated by Sidekick is for learning and experimentation purposes only.
import json

def speaker_times(transcribe_json):
    speaker_durations = {}
    segments = transcribe_json['results']['speaker_labels']['segments']
    for segment in segments:
        label = segment['speaker_label']
        start = float(segment['start_time'])
        end = float(segment['end_time'])
        duration = end - start
        speaker_durations[label] = speaker_durations.get(label, 0) + duration
    return speaker_durations

# Example usage:
with open('TestJob8MultiDiarization.json', 'r') as f:
    transcribe_json = json.load(f)
speaker_talk_times = speaker_times(transcribe_json)
for speaker, time in speaker_talk_times.items():
    print(f"{speaker}: {time:.2f} seconds")
if __name__ == '__main__':
    print('Python')
